[package]
name = "solana_simple_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "solana_simple_program"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.26"
borsh = { version = "1.5.6", features = ["derive"] }

